### ISSUE TITLE
It is a good work!

### ISSUE THREAD

**Issue by aisegmentcn** [z-x-yang/CFBI#1]
Thank you!

**Comment by z-x-yang** [comment]
I'm glad you're interested in our work. We'll release the code after the paper is accepted. Currently, our paper is under review from one of the top CV conferences.

**Comment by ofirkris** [comment]
Interested too - I've seen the paper was published - great work!

**Comment by ayoggchen** [comment]
congratulations! And looking forward to see your code!

**Comment by z-x-yang** [comment]
> congratulations! And looking forward to see your code!

Thanks! If everything goes well, I'll check and release all the code by the end of this month.
