### ISSUE TITLE
Clarification on usage - 

### ISSUE THREAD

**Issue by 8secz-johndpope** [z-x-yang/CFBI#10]
how to input a generic video / mp4 ?

for example - this repo provides some pointers 
https://github.com/senguptaumd/Background-Matting

spit out individual pngs
```shell
cd Background-Matting/sample_video
mkdir input background
ffmpeg -i teaser.mov input/%04d_img.png -hide_banner

```

apply segmentation

```shell
cd Background-Matting/models/research/
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
cd ../..
python test_segmentation_deeplab.py -i sample_video/input

```

I can see the script  ./ytb_eval_fast.sh evaluating - but where do the files go/ where are they created? I couldn't find them.(I'm on ssh in the cloud)
 **locate -b '00005.jpg'** didn't turn up any results

Prcessing Seq 0557542e8d [11/474]:
Ref Frame: 00000.jpg, Time: 0.09423136711120605
Frame: 00005.jpg, Obj Num: 1, Time: 1.1294879913330078
Frame: 00010.jpg, Obj Num: 1, Time: 0.855078935623169
Frame: 00015.jpg, Obj Num: 1, Time: 0.8564548492431641
Frame: 00020.jpg, Obj Num: 1, Time: 0.84938645362854
Frame: 00025.jpg, Obj Num: 1, Time: 0.8649313449859619
Frame: 00030.jpg, Obj Num: 1, Time: 0.8523914813995361
Frame: 00035.jpg, Obj Num: 1, Time: 0.8554131984710693
Frame: 00040.jpg, Obj Num: 1, Time: 0.8590476512908936
Frame: 00045.jpg, Obj Num: 1, Time: 0.8608062267303467
Frame: 00050.jpg, Obj Num: 1, Time: 0.845700740814209
Frame: 00055.jpg, Obj Num: 1, Time: 0.8705801963806152
Frame: 00060.jpg, Obj Num: 1, Time: 0.8516411781311035
Frame: 00065.jpg, Obj Num: 1, Time: 0.8602666854858398
Frame: 00070.jpg, Obj Num: 1, Time: 0.8541202545166016
Frame: 00075.jpg, Obj Num: 1, Time: 0.8581304550170898
Frame: 00080.jpg, Obj Num: 1, Time: 0.8512144088745117
Frame: 00085.jpg, Obj Num: 1, Time: 0.8659780025482178
Frame: 00090.jpg, Obj Num: 1, Time: 0.8513703346252441
Frame: 00095.jpg, Obj Num: 1, Time: 0.8629040718078613
Frame: 00100.jpg, Obj Num: 1, Time: 0.8581538200378418
Frame: 00105.jpg, Obj Num: 1, Time: 0.8561139106750488
Frame: 00110.jpg, Obj Num: 1, Time: 0.8489248752593994
Frame: 00115.jpg, Obj Num: 1, Time: 0.8641960620880127
Frame: 00120.jpg, Obj Num: 1, Time: 0.8525502681732178
Frame: 00125.jpg, Obj Num: 1, Time: 0.8621423244476318
Frame: 00130.jpg, Obj Num: 1, Time: 0.8552994728088379
Frame: 00135.jpg, Obj Num: 1, Time: 0.8562443256378174
Frame: 00140.jpg, Obj Num: 1, Time: 0.8510112762451172
Frame: 00145.jpg, Obj Num: 1, Time: 0.8548166751861572
Frame: 00150.jpg, Obj Num: 1, Time: 0.8519599437713623
Frame: 00155.jpg, Obj Num: 1, Time: 0.8683714866638184
Frame: 00160.jpg, Obj Num: 1, Time: 0.8495943546295166
Frame: 00165.jpg, Obj Num: 1, Time: 0.863872766494751
Frame: 00170.jpg, Obj Num: 1, Time: 0.8625590801239014
Frame: 00175.jpg, Obj Num: 1, Time: 0.8523445129394531

UPDATE
I rsync content back to my desktop and can see DAVIS/annotations/480p/bear and a lot of the images. eg. bmx etc 
I'm not sure how to input a new video and where the output is supposed to end up.

UPDATE 2
running this I can see files show up in check point folder
 rsync --exclude '.git' --progress -Pav -e "ssh -i p2-machinelearning.pem" ubuntu@ec2-xxxxxxxxcompute-1.amazonaws.com://home/ubuntu/gitWorkspace/CFBI /home/jp/Documents/gitWorkspace/

00%   10.36kB/s    0:00:00 (xfr#327, to-chk=33/27176)
CFBI/result/resnet101_cfbi/eval/youtubevos/youtubevos_resnet101_cfbi_ckpt_unknown/Annotations/056a2ff390/
CFBI/result/resnet101_cfbi/eval/youtubevos/youtubevos_resnet101_cfbi_ckpt_unknown/Annotations/056a2ff390/00000.png
          2,777 100%    6.80kB/s    0:00:00 (xfr#328, to-chk=32/27176)
CFBI/result/resnet101_cfbi/eval/youtubevos/youtubevos_resnet101_cfbi_ckpt_unknown/Annotations/056a2ff390/00005.png
          3,703 100%    9.06kB/s    0:00:00 (xfr#329, to-chk=31/27176)
CFBI/result/resnet101_cfbi/eval/youtubevos/youtubevos_resnet101_cfbi_ckpt_unknown/Annotations/056a2ff390/00010.png
          3,724 100%    9.11kB/s    0:00:00 (xfr#330, to-chk=30/27176)
CFBI/result/resnet101_cfbi/eval/youtubevos/youtubevos_resnet101_cfbi_ckpt_unknown/Annotations/056a2ff390/00015.png
          3,710 100%    9.08kB/s    0:00:00 (xfr#331, to-chk=29/27176)
CFBI/result/resnet101_cfbi/eval/youtubevos/youtubevos_resnet101_cfbi_ckpt_unknown/Annotations/056a2ff390/00020.png
          3,907 100%    9.54kB/s    0:00:00 (xfr#332, to-chk=28/27176)
CFBI/result/resnet101_cfbi/eval/youtubevos/youtubevos_resnet101_cfbi_ckpt_unknown/Annotations/056a2ff390/00025.png
          3,899 100%    9.52kB/s    0:00:00 (xfr#333, to-chk=27/27176)
CFBI/result/resnet101_cfbi/eval/youtubevos/youtubevos_resnet101_cfbi_ckpt_unknown/Annotations/056a2ff390/00030.png
          3,740 100%    9.13kB/s    0:00:00 (xfr#334, to-chk=26/27176)
CFBI/result/resnet101_cfbi/eval/youtubevos/youtubevos_resnet101_cfbi_ckpt_unknown/Annotations/056a2ff390/00035.png

DIgging deeper I can see the youtube input 
![Screenshot from 2020-08-24 15-52-57](https://user-images.githubusercontent.com/50567111/91008559-f95aad00-e621-11ea-9c49-0256cbe24355.png)

should be able to craft some script to input a file easily enough. I'll post once I have it ready. (should be just as above with ffmpeg - just need to tweak inputs / and how the eval script picks things up.)

![Screenshot from 2020-08-24 16-00-58](https://user-images.githubusercontent.com/50567111/91009075-1b086400-e623-11ea-9f9c-758bf358bf0f.png)

![Screenshot from 2020-08-24 15-52-57](https://user-images.githubusercontent.com/50567111/91009082-1e9beb00-e623-11ea-988c-946c85099d55.png)

UPDATE 3
it seems the meta data.json is tangled with eval script - it would be nice to be able to just throw an mp4 / mov file and process video frames /png.

**Comment by z-x-yang** [comment]
Currently, we have not a script to input a generic video / mp4. 

If you want to evaluate CFBI on your data, please convert your data into a format like the DAVIS dataset.

For example, place a sequence of images in `DAVIS/JPEGImages/480p/bear`, and place the mask of the first image in `DAVIS/annotations/480p/bear`. Then, run `davis_eval.sh`.

**Comment by 8secz-johndpope** [comment]
ok thanks
