### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by zgf6781882** [z-x-yang/CFBI#13]
Hi author:
Thanks for your great work!
I am very interested in your work and looking forward to your training code. I have sent two emails to you for asking the training code, but I don't receive any reply.  My email addresses are 1439402142@qq.com and 1909853vii30003@student.must.edu.mo

**Comment by z-x-yang** [comment]
Done!

**Comment by gewenbin0992** [comment]
@z-x-yang Hi Zongxin, I also send an email asking for the training code, but I don't receive any reply. My email address is gewenbin292@bit.edu.cn

**Comment by z-x-yang** [comment]
> @z-x-yang Hi Zongxin, I also send an email asking for the training code, but I don't receive any reply. My email address is [gewenbin292@bit.edu.cn](mailto:gewenbin292@bit.edu.cn)

Sorry, I haven't received any emails from your address. Please send a requirement to my email (zongxin.yang@student.uts.edu.au) again.

**Comment by gewenbin0992** [comment]
@z-x-yang I sent it again. (My email address is gewenbin292@bit.edu.cn)

**Comment by z-x-yang** [comment]
> @z-x-yang I sent it again. (My email address is [gewenbin292@bit.edu.cn](mailto:gewenbin292@bit.edu.cn))

@gewenbin0992  Done!

**Comment by hwh-hit** [comment]
Hi，zongxing，I  send an email asking for the training code, but I don't receive any reply.  My email address is 991185721@qq.com, looking forward to your reply.

**Comment by z-x-yang** [comment]
@hwh-hit Done!

**Comment by hwh-hit** [comment]
@z-x-yang thanks a lot

**Comment by micoene** [comment]
Hi, I also send you an email about the training code but didnt reveive any reply yet. My name is Michael Coene.
I must already thank you for your great work, the code works really well on issues it has never seen before.

**Comment by z-x-yang** [comment]
@micoene Done!

**Comment by rogerchang23424** [comment]
Hi author,
I have sent email for asking the training code, but I don't receive any reply. 
My email address is s108062650@m108.nthu.edu.tw, hoping for you reply.

**Comment by z-x-yang** [comment]
@rogerchang23424 Done!

**Comment by rogerchang23424** [comment]
Thanks a lot!

**Comment by Ximoi** [comment]
Hi author, thank you for your great work, i also send email for asking the training code, and i hope for your reply.
