### ISSUE TITLE
inference on 4k images.

### ISSUE THREAD

**Issue by aiwithshekhar** [z-x-yang/CFBI#14]
how can i run inference on 4k( 3840 x 2160) images, as presently DAVIS or youtube-vos uses 480p resolution.

**Comment by z-x-yang** [comment]
Please set `--max_long_edge` to a number larger than 2160 during inference.

Running inference on such huge images will take a large amount of GPU memory. I'm not sure how much memory is enough.

**Comment by aiwithshekhar** [comment]
thanks for the reply, i get this error message, `RuntimeError: CUDA out of memory. Tried to allocate 3.19 GiB (GPU 3; 10.92 GiB total capacity; 7.00 GiB already allocated; 3.12 GiB free; 7.16 GiB reserved in total by PyTorch)`. I am using GTX 1080 having RAM (11178MB).

**Comment by z-x-yang** [comment]
For reducing the memory usage, you can refer to this [issue](https://github.com/z-x-yang/CFBI/issues/11#issuecomment-683438060).

But, I suppose 11G memory is not enough for 4k images...

**Comment by johndpope** [comment]
you can get k80 / 32gb of VRAM on ec2 spot pricing for $0.27

**Comment by aiwithshekhar** [comment]
Thanks @z-x-yang  and @johndpope for your help!

**Comment by aiwithshekhar** [comment]
For 480p, by any means is it possible for inference on CPU, below is the lowest memory usage on mobilent.

MobileNetV2-Fast-CFBI-DAVIS  - 3053MiB
MobileNetV2-CFBI-DAVIS  - 6971MiB

**Comment by z-x-yang** [comment]
I've not tried to infer on CPU. Maybe you can try it by removing all the `.cuda()` in `eval_manager.py`.
