### ISSUE TITLE
including new labels for new object as all the objects can't appear in the first frame.

### ISSUE THREAD

**Issue by aiwithshekhar** [z-x-yang/CFBI#15]
As it has been mentioned in the comments of [eval_manager.py](https://github.com/z-x-yang/CFBI/blob/master/networks/engine/eval_manager.py) line number 194, including new labels for new object. Is it done using flip argument, if not can you please elaborate how it's done.
```
if sample['meta']['flip']:
    all_pred = flip_tensor(all_pred, 3)
# In YouTube-VOS, not all the objects appear in the first frame for the first time. 
# Thus, we have to introduce new labels for new objects, if necessary.
```

**Comment by z-x-yang** [comment]
See [this issue](https://github.com/z-x-yang/CFBI/issues/6#issuecomment-675289432) for an explanation.

I just spatially Concat all the reference labels and reference embedding, if there is more than one reference frame.

**Comment by z-x-yang** [comment]
If there are no more questions, I'll close this issue. THX!
