### ISSUE TITLE
foreground and background predictions confusions.

### ISSUE THREAD

**Issue by aiwithshekhar** [z-x-yang/CFBI#16]
I have tried using Davis-2017-test-dev sequence named horsejump-stick, there the algorithm prediction confuses the foreground and backgound. Below are the few images. can you please let me know what may have caused this.

![00025](https://user-images.githubusercontent.com/31220538/93336551-879f0900-f845-11ea-9156-8c5dba300357.png)
![00030](https://user-images.githubusercontent.com/31220538/93336558-8a99f980-f845-11ea-92cb-17b98b455444.png)

**Comment by z-x-yang** [comment]
Did you use the pretrained CFBI-DAVIS? I found the link of ResNet101-CFBI-DAVIS was the same as ResNet101-CFBI. This was a mistake, and I have updated the link.

**Comment by z-x-yang** [comment]
CFBI is effective in relieving the background confusion problem, but this doesn't mean that CFBI can totally overcome it. In some cases, background confusion can be an ill-posed problem.

But the case in your example seems not too hard, I suppose a better training with more similar scenes should overcome this case.  It seems that there are few shots containing similar horses in both DAVIS and YouTube-VOS.

**Comment by aiwithshekhar** [comment]
thanks for replying, actually for the above prediction i had used mobilenetv2_cfbi_davis. I tried with above mentioned youtube pretrained weights (resnet101_cfbi) & the results looks good.
![00025](https://user-images.githubusercontent.com/31220538/93386532-770e8300-f885-11ea-9c3e-f898c794623d.png)
![00030](https://user-images.githubusercontent.com/31220538/93386541-7970dd00-f885-11ea-9f0d-e375bbab6aec.png)

**Comment by z-x-yang** [comment]
Reasonable.

MobileNet-V2 is much weaker than ResNet-101.

**Comment by z-x-yang** [comment]
I suppose your question has been solved, and I'll close this issue. THX.

**Comment by aiwithshekhar** [comment]
@z-x-yang One last question, for youtube vos we have a meta.json file where information about every object frame number is provided. But for any test sequence, it would be little difficult to know this information beforehand.
Can you suggest something for this.

**Comment by z-x-yang** [comment]
For each test sequence, object frame numbers are the total sequence, even if the object is fully occluded in some frames.

This is reasonable. Just like you will not know when an object will be occluded in real world. You have to process all the frames.

**Comment by aiwithshekhar** [comment]
Thanks for answering! what i meant was suppose Seq "00f88c4f0a" in YouTube-VOS, here in meta json we explicitly provide information about when rider will appear(10th frame) and when skateboard(20th frame) will appear. But in any new test case sequence knowing these information beforehand will be difficult.

**Comment by z-x-yang** [comment]
It is necessary for semi-supervised video object segmentation to know when an object appears and this object's mask at this time.  Semi-supervised VOS is only responsible for tracking and segmenting your object (s) after given such information.

If you don't know when an object appears, you have to detect it by yourself. And this task is video instance segmentation.

**Comment by aiwithshekhar** [comment]
Thanks a lot for your patience throughout.
