### ISSUE TITLE
About the distance metric

### ISSUE THREAD

**Issue by XiaLiPKU** [z-x-yang/CFBI#17]
https://github.com/z-x-yang/CFBI/blob/5da872e268a25240eea9952d801f02b94b60be04/networks/layers/matching.py#L38
The distance metric is simply the l2-distance, as shown above.
However, in your paper, the distance is defined as Eq.1.
So, which one is better?

**Comment by z-x-yang** [comment]
This is just the same distance in our paper.

||x-y||^2=x^2-2xy+y^2

The latter format is more computationally efficient.

**Comment by XiaLiPKU** [comment]
> This is just the same distance in our paper.
> 
> ||x-y||^2=sum(x^2)-2*sum(xy)+sum(y^2)
> 
> The latter format is more computationally efficient.

But in the paper, the equation is 1 - 2 / (1 + exp(||x -y||^2 + bias)

**Comment by XiaLiPKU** [comment]
> But in the paper, the equation is 1 - 2 / (1 + exp(||x -y||^2 + bias)
This difference doesn't influence the minimum indexes but influences the minimum values

**Comment by z-x-yang** [comment]
[1 - 2 / (1 + exp(||x -y||^2 + bias)](https://github.com/z-x-yang/CFBI/blob/5da872e268a25240eea9952d801f02b94b60be04/networks/layers/matching.py#L308).

**Comment by XiaLiPKU** [comment]
> [1 - 2 / (1 + exp(||x -y||^2 + bias)](https://github.com/z-x-yang/CFBI/blob/5da872e268a25240eea9952d801f02b94b60be04/networks/layers/matching.py#L308).
> 
> See here.

Got it, Thank you very much!

**Comment by z-x-yang** [comment]
Sure thing.
