### ISSUE TITLE
About the backbone file.

### ISSUE THREAD

**Issue by STverr7** [z-x-yang/CFBI#18]
I notice that the backbone you choose is res100+deeplabv3p, could you please provide the link to download the original file of this backbone(resnet101-deeplabv3p.pth.tar)? Thank you.

**Comment by z-x-yang** [comment]
[ResNet101-DeepLabV3+](https://drive.google.com/file/d/1H3yUShfPqzxSt-nHJP-zYSbbu2o_RQQu/view?usp=sharing).
