### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by cctgem** [z-x-yang/CFBI#2]
I'm implementing CFBI but i have some question.
1.How to apply collaborative instance-level attention vector to CE?
2.How to fuse low-level backbone features and decoded feature? Just concat?
Thank you.

**Comment by z-x-yang** [comment]
1. After you get the instance-level attention (IA) vector, you need to apply IA gate before every ResBlock, ASPP, and Decoder of CE. The code of IA gate is below:
`class IA_gate(nn.Module):
    def __init__(self, in_dim, out_dim):
        super(IA_gate, self).__init__()
        self.IA = nn.Linear(in_dim, out_dim)

    def forward(self, x, IA_head):
        # x: a feature in CE
        # IA_head: the collaborative instance-level attention vector
        a = self.IA(IA_head)
        a = 1. + torch.tanh(a)
        a = a.unsqueeze(-1).unsqueeze(-1)
        x = a * x
        return x`
Besides, we use a FC layer to generate the weight and bias of the last output Conv of CE. The input of this FC layer is the IA vector.

2. For realizing Decoder, you can refer to the code [here](https://github.com/jfzhang95/pytorch-deeplab-xception/blob/master/modeling/decoder.py).

**Comment by cctgem** [comment]
Thank you so much.
