### ISSUE TITLE
How FPS is calculated

### ISSUE THREAD

**Issue by bo-miao** [z-x-yang/CFBI#21]
Hi,

May I know how to calculate FPS? 

In dataset such as DAVIS2017, each frame might contain several objects to track, but the proposed method needs to track each object separately in each frame. In that case, how the FPS is calculated?  If the object number is _N_ and each object segmentation time cost is _T_ in one frame, does it mean _T*N_ s is needed in each frame?

Thanks!

**Comment by z-x-yang** [comment]
We calculated the multi-object FPS. For example, if a video contains 5 objects, we will calculate the inference time for completing all the object predictions.

CFBI tracks all the objects in a parallel way. The backbone feature of CFBI is shared for all the objects in a video. And only the ensembler processed each object separately but in parallel. Thus it will take only a little more computation to process multiple objects, compared to a single object.

**Comment by bo-miao** [comment]
Thanks for your answer.
