### ISSUE TITLE
YouTube-VOS 2019 Split Validation Set Missing meta.json 

### ISSUE THREAD

**Issue by rsomani95** [z-x-yang/CFBI#22]
Hello. Thank you for sharing your work. Very fascinating project!

The [2019 validation split](https://drive.google.com/file/d/1o586Wjya-f2ohxYf9C1RlRH-gkrzGS8t/view) mentioned in the README doesn't have a `meta.json` which breaks the evaluation script

**Comment by z-x-yang** [comment]
I checked the package, which contains "meta.json."

**Comment by z-x-yang** [comment]
It seems that the problem has been solved, and I'll close this issue. If you have more questions, you can re-open this issue.
