### ISSUE TITLE
make key mask frame ?

### ISSUE THREAD

**Issue by luoww1992** [z-x-yang/CFBI#23]
how to make the first key frame with mask ?
it is different to other 24bit color image.
I try to make it, but the result is bad.

**Comment by z-x-yang** [comment]
Refer to this [issue](https://github.com/z-x-yang/CFBI/issues/20#issuecomment-736351851).

A mask file is an 8-bit greyscale image, whose colour is from an inside colour palette. The palette is not necessary for inference.
