### ISSUE TITLE
different and weird result 

### ISSUE THREAD

**Issue by luoww1992** [z-x-yang/CFBI#24]
i run the code with the bigs folder in dataset,
while  i test it with default dataset, result is good, like this :
![good](https://user-images.githubusercontent.com/45957595/105853861-1eb07480-6021-11eb-94ad-ddc1c2d59e5b.png)

but when i change the mask in first mask image, it shows me some weird result, like this,
![bad](https://user-images.githubusercontent.com/45957595/105854127-751db300-6021-11eb-9d86-2069afd351a7.png)

left in photo is the first key frame.

**Comment by z-x-yang** [comment]
I never come with this case.
Can you describe the change you made in detail?

**Comment by luoww1992** [comment]
i will try to test it, thanks !
