### ISSUE TITLE
About reproducing the results on the DAVIS2017 dataset

### ISSUE THREAD

**Issue by Avocado5818** [z-x-yang/CFBI#25]
Hi, I want to reproduce the result on DAVIS2017 dataset, but the config file is only trained on the youtube and finetuned on the davis2017. I would like to ask if you only train on davis2017 and test on davis2017, there are additional config files or need to be adjusted parameters?

Thanks!

**Comment by z-x-yang** [comment]
When training with only DAVIS2017, you could slightly modify the fine-tuning config. That is removing the training set of YouTube-VOS and setting the pre-trained model as the config of YouTube-VOS.

Notably, it is very easy to over-fit DAVIS-2017 by training with only DAVIS-2017. The best performance should be achieved around 30K steps (50K steps in total). Thus, you could evaluate the checkpoints after 25K steps to find the best one. To ensure enough checkpoints be kept, you could increase the number of TRAIN_MAX_KEEP_CKPT in the config.

**Comment by Avocado5818** [comment]
I Got it, thank you very much for your reply!
