### ISSUE TITLE
About find the best checkpoint

### ISSUE THREAD

**Issue by huanglf714** [z-x-yang/CFBI#26]
Hi!
When I want to train the model on the dataset DAVIS and Youtube-VOS, I find the code only records the loss and iou curves on the 'train' split but without the curves on the 'val' split, then how can I find the best model on the 'val' split? Is the only way is to test on the 'val' split one by one?
Could you tell me how you find the best checkpoint?
Thanks very much!

**Comment by z-x-yang** [comment]
In our experiments, we checked only the last four checkpoints to select the best one.

Generally, the last checkpoint is always the best checkpoint.

**Comment by huanglf714** [comment]
Got it! Thanks for your reply!
But if always trained with the YouTube-VOS, it is hard and time-consuming to test and evaluate the effectiveness of a specific module part.

**Comment by z-x-yang** [comment]
It's OK to seek efficient evaluations on small benchmarks.

In my experience, the best checkpoint should always be achieved at about half of the training schedule when training with only DAVIS.
