### ISSUE TITLE
RuntimeError: open(/sharefile): Permission denied

### ISSUE THREAD

**Issue by longmalongma** [z-x-yang/CFBI#28]
Hi, thanks for your great work! When I try to run python tools/train_net.py --config configs.resnet101_cfbi --da
taset youtubevos, I meet this problem, can you help me ? 
File "/home/longma/anaconda2/envs/p3torchstm/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 484, in _new_process_group_helper
    timeout=timeout)
RuntimeError: open(/sharefile): Permission denied

**Comment by z-x-yang** [comment]
You could try to set self.DIST_URL = “tcp://127.0.0.1:12345” in the config file.

The URL is used for distributed multi-GPU communication. More details can be found in [here](https://pytorch.org/docs/stable/distributed.html).

**Comment by longmalongma** [comment]
> You could try to set self.DIST_URL = “tcp://127.0.0.1:12345” in the config file.
> 
> The URL is used for distributed multi-GPU communication. More details can be found in [here](https://pytorch.org/docs/stable/distributed.html).

I have tried it, but it didn't work, and the error was still there.

**Comment by z-x-yang** [comment]
What was the latter error?

**Comment by longmalongma** [comment]
> What was the latter error?

![image](https://user-images.githubusercontent.com/40291722/113513388-15e99b00-959c-11eb-8ba7-57506385a504.png)


鑫哥，还是这个错误：RuntimeError: open(/sharefile): Permission denied，我用我自己的单卡和多卡服务器都是这个报错，不知道是咋回事？

**Comment by z-x-yang** [comment]
说明你的修改根本没有生效，生效了不会出现sharefile。

**Comment by longmalongma** [comment]
> 说明你的修改根本没有生效，生效了不会出现sharefile。你自己的code的问题，你检查一下吧。

好的，鑫哥，我是在复现您的代码的时候遇到的这个问题，没有做任何改动，我在configs下面的三个文件都修改为DIST_URL = “tcp://127.0.0.1:12345，我再好好检查一下，不知道问题出在哪了。

**Comment by z-x-yang** [comment]
你看看训练开始的时候print出来的参数，就知道你改动到了没有。

**Comment by longmalongma** [comment]
> 你看看训练开始的时候print出来的参数，就知道你改动到了没有。

好的，谢谢鑫哥，我再仔细检查一下。
