### ISSUE TITLE
What are the meanings of "join label" and  sample['meta']['flip']

### ISSUE THREAD

**Issue by houhouhouhou11** [z-x-yang/CFBI#29]
Hello:
     thanks for your sharing the perfect work! I have question in eval_manager.py which is  the meanings of "join label" and  sample['meta']['flip'].What are they represent?
     Thank you very much!

**Comment by z-x-yang** [comment]
1) "join label". Please refer to this [issue](https://github.com/z-x-yang/CFBI/issues/6).

2) "flip," used for testing time augmentation, flipping. Unable in default.

**Comment by houhouhouhou11** [comment]
@z-x-yang sorry, I haven't understand clearly! Is  "flip"  used for testing time augmentation?                                 what is the meaning of all_pred = flip_tensor(all_pred, 3) ? thank you

**Comment by z-x-yang** [comment]
When enabling flipping, the videos will be additionally evaluated by flipping each frame horizontally. Thus, we have to flip back the flipped predictions before ensembling both un-flipped and flipped results.

**Comment by z-x-yang** [comment]
The flipping ensemble has been commonly used in semantic segmentation. We just apply the same strategy to video object segmentation.
