### ISSUE TITLE
ann_f 调用前没有找到定义

### ISSUE THREAD

**Issue by longmalongma** [z-x-yang/CFBI#30]
![image](https://user-images.githubusercontent.com/40291722/113822179-b19f2500-97af-11eb-8449-95ce97c47eb1.png)

鑫哥，这个类YOUTUBE_VOS_Train里面的这个属性ann_f你好像调用前没有找到定义，应该怎么定义？另外，我只有一个四卡的2080ti可以运行你的程序吗？

**Comment by z-x-yang** [comment]
请一步一步参照ReadMe中的指示来训练。

你当前的问题代表你没有按照指示把训练数据集放在正确的文件夹下。

**Comment by longmalongma** [comment]
> 请一步一步参照ReadMe中的指示来训练。
> 
> 你当前的问题代表你没有按照指示把训练数据集放在正确的文件夹下。

哦哦，好的，谢谢鑫哥。
