### ISSUE TITLE
why do u use the 3 and 5 in Youtube and davis respectively?

### ISSUE THREAD

**Issue by zxyyxzz** [z-x-yang/CFBI#31]
Hi yang:

i see that DATA_CURR_SEQ_LEN in your code is 3 and 5 in the two different datasets, 
i can't understand why davis is 3, and youtube is 5。

could you reply me ?

Thanks:-)~~~！！！

**Comment by z-x-yang** [comment]
YouTube is 3, and DAVIS is 5.

The reason is that DAVIS has a much faster frame rate than YouTube (24FPS vs 6FPS). Thus, we have to use a longer sequence length for DAVIS to maintain enough temporal duration.

**Comment by zxyyxzz** [comment]
> YouTube is 3, and DAVIS is 5.
> 
> The reason is that DAVIS has a much faster frame rate than YouTube (24FPS vs 6FPS). Thus, we have to use a longer sequence length for DAVIS to maintain enough temporal duration.

Thanks for your reply:
   But i still can't understand that why the longer sequence length can maintain the temporal duration,  
  When i train the model, the longer sequence length can optimize the model more times within a seq， but why do this is benificial to maintain temporal duration?

**Comment by zxyyxzz** [comment]
> YouTube is 3, and DAVIS is 5.
> 
> The reason is that DAVIS has a much faster frame rate than YouTube (24FPS vs 6FPS). Thus, we have to use a longer sequence length for DAVIS to maintain enough temporal duration.

Thanks for your reply:
   But i still can't understand that why the longer sequence length can maintain the temporal duration,  
  When i train the model, the longer sequence length can optimize the model more times within a seq， but why do this is benificial to maintain temporal duration?

**Comment by z-x-yang** [comment]
It's simple...

6 continuous frames on YouTube-VOS is 1 second. But, much more 24 continuous frames on DAVIS is 1 second.

**Comment by zxyyxzz** [comment]
> It's simple...
> 
> 6 continuous frames on YouTube-VOS is 1 second. But, much more 24 continuous frames on DAVIS is 1 second.


感觉用英文表达不清楚我的意思，可能我陷入了死胡同，比如说davis是1秒24帧，youtube1秒6帧，训练的时候一个用5一个用3，这个5，在代码里其实就是在当前序列的5帧得到结果，更新了5次，youtube是更新3次，davis比Youtube多更新了2次，我的意思就是多更新这2次，模型就会更好吗？帧率跟更新次数有什么关系呢，为什么帧率越快，就要多更新几次，多更新几次网络就能学习的更好吗？

有点转不过弯来，

**Comment by z-x-yang** [comment]
时间跨度短的话，很多事件是很难遇到的，比如物体被遮挡又出现。因为遮挡一般会持续一段时间。

帧数多的话，也可以相当于提升batch size，因为多帧的梯度是取平均的。

实际情况下你可以把帧数当做一个超参数，实验上就是现在这个参数比较robust。

**Comment by zxyyxzz** [comment]
> 时间跨度短的话，很多事件是很难遇到的，比如物体被遮挡又出现。因为遮挡一般会持续一段时间。
> 
> 帧数多的话，也可以相当于提升batch size，因为多帧的梯度是取平均的。
> 
> 实际情况下你可以把帧数当做一个超参数，实验上就是现在这个参数比较robust。

解释的非常清楚，我明白了，谢谢你！~~
