### ISSUE TITLE
DATA_RANDOM_GAP_YTB parameter during training

### ISSUE THREAD

**Issue by vidit98** [z-x-yang/CFBI#32]
Hi, could you please explain what is rand_gap parameter in the data loader? It seems that due to it the frames can be non-continuous as well during training.

**Comment by z-x-yang** [comment]
We apply random interval as an augmentation when sampling frame sequence. Most of the adjacent two frames share a nearly identical scene, which is too easy for CFBI. The random interval is helpful to encourage faster and harder motions.

**Comment by vidit98** [comment]
Thanks for the prompt reply!
