### ISSUE TITLE
What's the difference between the models used in davis17 and youtubevos when evaluation

### ISSUE THREAD

**Issue by houhouhouhou11** [z-x-yang/CFBI#33]
Hello:
      Thanks for your reply! I have another question :
                YouTube-VOS: Download pretrained CFBI, ResNet101-CFBI, to pretrain_models.
                DAVIS: Download pretrained CFBI, ResNet101-CFBI-DAVIS, to pretrain_models.
      Does  ResNet101-CFBI and  ResNet101-CFBI-DAVIS have any difference?
     Thank you very much!

**Comment by z-x-yang** [comment]
They are trained on different datasets. No other difference.
