### ISSUE TITLE
How to do quantitative testing?

### ISSUE THREAD

**Issue by longmalongma** [z-x-yang/CFBI#34]
how do you perform quantitative tests to generate specific ones? You don’t seem to publish the code for quantitative testing?
![image](https://user-images.githubusercontent.com/40291722/114293237-06e87880-9ac7-11eb-9856-de70a41722cb.png)

**Comment by longmalongma** [comment]
> how do you perform quantitative tests to generate specific ones? You don’t seem to publish the code for quantitative testing?
> ![image](https://user-images.githubusercontent.com/40291722/114293237-06e87880-9ac7-11eb-9856-de70a41722cb.png)

I got it!

**Comment by longmalongma** [comment]
> > how do you perform quantitative tests to generate specific ones? You don’t seem to publish the code for quantitative testing?
> > ![image](https://user-images.githubusercontent.com/40291722/114293237-06e87880-9ac7-11eb-9856-de70a41722cb.png)
> 
> I got it!

How do I get quantitative results on the DAVIS2017 dataset?Do you provide the code to calculate the quantitative results

**Comment by z-x-yang** [comment]
Please refer to Getting Started.

**Comment by longmalongma** [comment]
> Please refer to Getting Started.



> Please refer to Getting Started.

Ok, thanks!
