### ISSUE TITLE
Multi-GPU

### ISSUE THREAD

**Issue by vavenCV** [z-x-yang/CFBI#35]
How can I use a multi-gpu setup with your code ? (really great btw)

**Comment by z-x-yang** [comment]
The default training setting uses 4 GPUs. You could change the GPU number in the config file.

The evaluation uses only one GPU.

**Comment by vavenCV** [comment]
It was for evaluation, on ytb-vos I always have a memory overflow even with 11Gb

**Comment by z-x-yang** [comment]
You could run fast CFBI, which is more efficient.
