### ISSUE TITLE
An error occurred during evaluation on the Davis dataset

### ISSUE THREAD

**Issue by longmalongma** [z-x-yang/CFBI#36]
Hi all,

This is my command I run and I got an unexpected error. I change the path to DAVIS correctly.

python evaluation_method.py --task semi-supervised --results_path my_results/semi-supervised 
Evaluating sequences for the semi-supervised task...
  0%|                                                    | 0/30 [00:00<?, ?it/s]bike-packing frame 00001 not found!
The frames have to be indexed PNG files placed inside the corespondent sequence folder.
The indexes have to match with the initial frame.
IOError: No such file or directory
  0%|                                                    | 0/30 [00:00<?, ?it/s]
Could anyone help me to figure out the problem?

**Comment by z-x-yang** [comment]
My code doesn't contain an "evaluation_method.py".
