### ISSUE TITLE
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1

### ISSUE THREAD

**Issue by longmalongma** [z-x-yang/CFBI#37]
![image](https://user-images.githubusercontent.com/40291722/115005669-aef0ae00-9eda-11eb-8e71-108a0640713b.png)

![image](https://user-images.githubusercontent.com/40291722/115005808-d9426b80-9eda-11eb-86b4-d0a02f36d907.png)

鑫哥，我有一个四卡2080ti的服务器，一个程序占了一部分内存，这是剩余的内存，要复现您的代码需要怎么设置resnet101_cfbi？batch_size和gpu怎么设置？我试了好多组合都是这个报错。

**Comment by z-x-yang** [comment]
As the printed log, "your training has been finished." Thus, the training process was exited.

**Comment by longmalongma** [comment]
> As the printed log, "your training has been finished." Thus, the training process was exited.

Thanks for your reply, how to start to retrain?

**Comment by z-x-yang** [comment]
Change the experiment name in your config.

An experiment can't be finished twice.

**Comment by longmalongma** [comment]
> config

Ok, thanks!
