### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by vavenCV** [z-x-yang/CFBI#38]
I'm trying to add more clues to the instance level attention.
I need to know when the sequential training is switching to another video during an epoch.
I've studied your train_manager.py and cfbi.py + datasets.py but I don't know if you feed the whole batch to cfbi.forward() or just one frame.
(sorry I'm kind of new to pytorch)

Is the whole batch fed into "train_manager.py, line 254." from "train_manager.py, line 217-223" or is there any separation?

**Comment by z-x-yang** [comment]
In each iteration of the sequential training, the prediction will be handled for a sequence of steps iteratively.

For each step, the whole batch of videos (each video contains a reference frame, a previous frame, and a current frame) will be fed to cfbi.forward().
