### ISSUE TITLE
Implementation detail

### ISSUE THREAD

**Issue by cctgem** [z-x-yang/CFBI#4]
I have some problems about implementation detail.

1.The feature strides of Resnet-101 backbone based deeplabv3+ are [4, 8, 8, 8], so i guest the low level feature before embedding  is the output of 'layer1' with stride 4. Is that right?

2.Limiting the number of object each frame less that 2 with crop size (384, 384) , batch size 1, and 5 frames, will cost 10G memory in my experiment. Is it because of my poor implementation?

Looking forward to your reply.

**Comment by z-x-yang** [comment]
1. Yes, the low-level feature is with a stride of 4.

2. In my implementation, crop size (465, 465) and batch size 2 will cost about 11G memory. I guess you did sequential training in a parallel way. In my sequential training, I forward each step separately and average the gradients in all the steps. After that, backward. In other words, the memory usage in each step is only 3 frames (one reference frame, one previous frame, and one current frame).

**Comment by cctgem** [comment]
That is clear, thanks.
