### ISSUE TITLE
Are you using FPN (Feature Pyramid Networks)?

### ISSUE THREAD

**Issue by longmalongma** [z-x-yang/CFBI#41]
Are you using FPN (Feature Pyramid Networks) in your network?

**Comment by longmalongma** [comment]
> Are you using FPN (Feature Pyramid Networks) in your network?

Do you have FPN of CFBI+ in your published code? I can't seem to find it.

**Comment by z-x-yang** [comment]
I've not published CFBI+.

**Comment by longmalongma** [comment]
> I've not published CFBI+.

Ok, Will you release CFBI+ in the future?
