### ISSUE TITLE
ensembler modification

### ISSUE THREAD

**Issue by vavenCV** [z-x-yang/CFBI#42]
I've made modification on the CollaborativeEnsembler(in ensembler.py) params.
In cfbi.py i've changed the size of the attention_dim param, for the self.dynamic_seghead.
I'm trying to negate the weigths from the various IA_gate in the CollaborativeEnsembler to retrain them with the new attention_dim size.
Problem is that I can't figure out where those are in the state_dict

**Comment by z-x-yang** [comment]
Maybe you could search the name of your param in all the keys of the model state_dict.
