### ISSUE TITLE
When will the code be ready.

### ISSUE THREAD

**Issue by cddlyf** [z-x-yang/CFBI#5]
Hi, authors, it has been about 30 days since the last commit, could you give a ETA to release the code?

**Comment by z-x-yang** [comment]
We're very happy that many people are paying attention to our work, and we will publish our code in mid-August!

**Comment by leemengxing** [comment]
thks，great job.

**Comment by IIAT-MR-LL** [comment]
@z-x-yang Will the training code also be available at mid-August?

**Comment by z-x-yang** [comment]
@IIAT-MR-LL Sure. Both training and evaluating.

**Comment by IIAT-MR-LL** [comment]
@z-x-yang Excellent, I am looking forward to seeing the release, I cannot await!

**Comment by vateye** [comment]
@z-x-yang Hi, will the code be released tomorrow?

**Comment by z-x-yang** [comment]
@vateye I'll release the code late today.

**Comment by z-x-yang** [comment]
@vateye @cddlyf @leemengxing @IIAT-MR-LL The code has been released now. I'll close this issue. Thanks for your patience.

**Comment by z-x-yang** [comment]
@vateye @cddlyf @leemengxing @IIAT-MR-LL 
Hi guys. Based on some necessary considerations, we have to withdraw the training code of CFBI. 

If you want to get the training code of CFBI, please contact us by email: <zongxin.yang@student.uts.edu.au>. And please inform us of your institution and the purpose of using CFBI in the email. Thank you for your understanding!

**Comment by z-x-yang** [comment]
@vateye @cddlyf @leemengxing @IIAT-MR-LL 
Some people cloned the training code before I withdrew it. However, we found a fatal mistake in Sequential Training. The mistake will decrease the performance by more than 1 point of performance. 

If you want a fixed version, please contact us by email.
