### ISSUE TITLE
About TEST_GLOBAL_ATROUS_RATE when evaluate Youtube 2018 using CFBI+

### ISSUE THREAD

**Issue by zhouweii234** [z-x-yang/CFBI#54]
It reports `TypeError: 'int' object is not subscriptable` at ./networks/cfbi/cfbip.py line 209, `atrous_rate=cfg.TEST_GLOBAL_ATROUS_RATE[scale_idx]`

You set 'TEST_GLOBAL_ATROUS_RATE ' = [2, 1, 1] in config/resnet101_cfbip.py and write `cfg.TEST_GLOBAL_ATROUS_RATE = args.global_atrous_rate` while the `global_atrous_rate` in config/resnet101_cfbip.py should I use as the value of `TEST_GLOBAL_ATROUS_RATE `

**Comment by z-x-yang** [comment]
Referring to [eval_net.py](https://github.com/z-x-yang/CFBI/blob/84f4bc31b007dabfa1a2879f2a6d3eefb39721a1/tools/eval_net.py#L59), `cfg.TEST_GLOBAL_ATROUS_RATE = [args.global_atrous_rate, 1, 1]` when using CFBI+.
