### ISSUE TITLE
A quick question about network construction

### ISSUE THREAD

**Issue by leeqiaogithub** [z-x-yang/CFBI#56]
There is a slight problem in file resnet.py. It seems the parameter "pretrained" is no use.
I wonder if it was a mistake or deliberate.If it's on purpose,Why don't we need to load pre-training weights?

**Comment by z-x-yang** [comment]
The pre-trained loading in resnet.py is useless since the loading of pretrained DeepLabV3+ includes the parameters of ResNet.

**Comment by leeqiaogithub** [comment]
I see,thanks for your reply
