### ISSUE TITLE
Expired download link of the pre-trained weight file of the backbone

### ISSUE THREAD

**Issue by JerryX1110** [z-x-yang/CFBI#58]
Hi Zongxin, I notice that the link to download the pre-trained weight file of the backbone (resnet101-deeplabv3p.pth.tar)[https://drive.google.com/file/d/1H3yUShfPqzxSt-nHJP-zYSbbu2o_RQQu/view?usp=sharing] has expired. Could you please update a new link? Thank you! : )

**Comment by JerryX1110** [comment]
I guess maybe the pre-trained weight file is from [this repo](https://github.com/VainF/DeepLabV3Plus-Pytorch) but I am not sure.

**Comment by z-x-yang** [comment]
I create a new link for [the backbone weight (resnet101-deeplabv3p.pth.tar)](https://drive.google.com/file/d/101jYpeGGG58Kywk03331PKKzv1wN5DL0/view?usp=sharing). Please take a try.

**Comment by JerryX1110** [comment]
Thanks for your timely reply!



---Original---
From: "Zongxin ***@***.***&gt;
Date: Thu, Mar 30, 2023 15:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [z-x-yang/CFBI] Expired download link of the pre-trained weightfile of the backbone (Issue #58)




 
I create a new link for the backbone weight (resnet101-deeplabv3p.pth.tar). Please take a try.
